version: '3'

services:
  nginx:
    image: chrisnharvey/magiclamp-nginx

    build:
      context: ./containers/nginx

    volumes:
      - ${PROJECTS_DIR}:/projects
      - ./data/ca:/ca
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/vhosts.conf
      - ./conf/nginx/ssl.ext:/etc/nginx/ssl.ext

    ports:
      - 80:80
      - 443:443

    networks:
      app_net:
        ipv4_address: 10.0.10.10

  postgres:
    image: postgres:12

    ports:
      - 5432:5432

    networks:
      app_net:
        ipv4_address: 10.0.10.15

  pgadmin:
    image: dpage/pgadmin4

    networks:
      app_net:
        ipv4_address: 10.0.10.16

    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"

    dns: 10.0.10.2

  mysql:
    image: mariadb:10.3-bionic

    volumes:
      - ./data/mysql:/var/lib/mysql
    
    command:
     'mysqld --innodb-flush-method=fsync'

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

    ports:
      - 3306:3306

    networks:
      app_net:
        ipv4_address: 10.0.10.20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    networks:
      app_net:
        ipv4_address: 10.0.10.22

    environment:
      - PMA_HOST=10.0.10.20
      - PMA_USER=root
      - PMA_PASSWORD=
      - MYSQL_ROOT_PASSWORD=gg

  mailcatcher:
    image: chrisnharvey/magiclamp-mailcatcher

    build:
      context: ./containers/mailcatcher

    ports:
      - 1025:1025

    networks:
      app_net:
        ipv4_address: 10.0.10.25

  workspace:
    image: chrisnharvey/magiclamp-workspace

    build:
      context: ./containers/workspace

    volumes:
      - ${PROJECTS_DIR}:/projects
      - ./data/workspace:/home/magicLAMP
      - ${SSH_DIR}:/home/magicLAMP/.ssh
      - .:/magicLAMP

    tty: true

    working_dir: /projects

    dns: 10.0.10.2

    networks:
      app_net:
        ipv4_address: 10.0.10.5

  dnsmasq:
    image: jpillora/dnsmasq

    volumes:
        - ./conf/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

    ports:
      - 53:53/udp
      - 5380:8080

    restart: always

    networks:
      app_net:
        ipv4_address: 10.0.10.53

  dnsmasq_internal:
    image: jpillora/dnsmasq

    volumes:
        - ./conf/dnsmasq_internal/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      app_net:
        ipv4_address: 10.0.10.2

  redis:
    image: redis:5.0

    ports:
      - 6379:6379

    networks:
      app_net:
        ipv4_address: 10.0.10.21

  selenium_chrome:
    image: selenium/standalone-chrome-debug

    ports:
      - 4444:4444
      - 4449:5900

    volumes:
      - /dev/shm:/dev/shm

    networks:
      app_net:
        ipv4_address: 10.0.10.30

    dns: 10.0.10.2

  selenium_firefox:
    image: selenium/standalone-firefox-debug

    ports:
      - 5555:4444
      - 5559:5900

    volumes:
      - /dev/shm:/dev/shm

    networks:
      app_net:
        ipv4_address: 10.0.10.31

    dns: 10.0.10.2

  php56:
      image: chrisnharvey/magiclamp-php56

      build:
        context: ./containers/php56

      volumes:
        - ${PROJECTS_DIR}:/projects
        - ./conf/php/5.6/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/php/5.6/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.56

      dns: 10.0.10.2

  php70:
      image: chrisnharvey/magiclamp-php70

      build:
        context: ./containers/php70

      volumes:
        - ${PROJECTS_DIR}:/projects
        - ./conf/php/7.0/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/php/7.0/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.70

      dns: 10.0.10.2

  php71:
      image: chrisnharvey/magiclamp-php71

      build:
        context: ./containers/php71

      volumes:
        - ${PROJECTS_DIR}:/projects
        - ./conf/php/7.1/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/php/7.1/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.71

      dns: 10.0.10.2

  php72:
      image: chrisnharvey/magiclamp-php72

      build:
        context: ./containers/php72

      volumes:
        - ${PROJECTS_DIR}:/projects
        - ./conf/php/7.2/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/php/7.2/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.72

      dns: 10.0.10.2

  php73:
      image: chrisnharvey/magiclamp-php73

      build:
        context: ./containers/php73

      volumes:
        - ${PROJECTS_DIR}:/projects
        - ./conf/php/7.3/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/php/7.3/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.73

      dns: 10.0.10.2

  php74:
      image: chrisnharvey/magiclamp-php74

      build:
        context: ./containers/php74

      volumes:
        - ${PROJECTS_DIR}:/projects
        - ./conf/php/7.4/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/php/7.4/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.74

      dns: 10.0.10.2

networks:
  app_net:
    driver: bridge

    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 10.0.10.0/24