version: '3'

services:
  web:
    image: nginx:latest

    volumes:
      - ${PROJECTS_DIR}:/projects
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/vhosts.conf

    ports:
      - 80:80

    networks:
      app_net:
        ipv4_address: 10.0.10.10

  mysql:
    image: mariadb:10.3-bionic

    volumes:
      - ./data/mysql:/var/lib/mysql
    
    command:
     'mysqld --innodb-flush-method=fsync'

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

    ports:
      - 3306:3306

    networks:
      app_net:
        ipv4_address: 10.0.10.20

  workspace:
    build:
      context: ./containers/workspace

    volumes:
      - ${PROJECTS_DIR}:/projects
      - ${SSH_DIR}:/home/magic/.ssh
      - .:/magicLAMP

    tty: true

    working_dir: /projects

    network_mode: host

  dnsmasq:
    image: jpillora/dnsmasq

    volumes:
        - ./conf/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

    ports:
      - 53:53/udp
      - 5380:8080

    restart: always

    networks:
      app_net:
        ipv4_address: 10.0.10.53

  dnsmasq_internal:
    image: jpillora/dnsmasq

    volumes:
        - ./conf/dnsmasq_internal/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      app_net:
        ipv4_address: 10.0.10.2

  php56:
      build:
        context: ./containers/php56

      volumes:
        - ${PROJECTS_DIR}:/projects

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.56

      dns: 10.0.10.53

  php70:
      build:
        context: ./containers/php70

      volumes:
        - ${PROJECTS_DIR}:/projects

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.70

      dns: 10.0.10.53

  php71:
      build:
        context: ./containers/php71

      volumes:
        - ${PROJECTS_DIR}:/projects

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.71

      dns: 10.0.10.53

  php72:
      build:
        context: ./containers/php72

      volumes:
        - ${PROJECTS_DIR}:/projects

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.72

      dns: 10.0.10.53

  php73:
      build:
        context: ./containers/php73

      volumes:
        - ${PROJECTS_DIR}:/projects

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.73

      dns: 10.0.10.53

  php74:
      build:
        context: ./containers/php74

      volumes:
        - ${PROJECTS_DIR}:/projects

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.74

      dns: 10.0.10.53

networks:
  app_net:
    driver: bridge

    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 10.0.10.0/24