version: '3'

services:
  nginx:
    image: chrisnharvey/magiclamp-nginx:${MAGICLAMP_VERSION}

    volumes:
      - ${PROJECTS_DIR:-./data/projects}:/projects
      - ./data/ca:/ca
      - ./conf/default/nginx/nginx.conf:/etc/nginx/conf.d/vhosts.conf
      - ./conf/default/nginx/ssl.ext:/etc/nginx/ssl.ext

    ports:
      - 80:80
      - 443:443

    networks:
      app_net:
        ipv4_address: 10.0.10.10

  postgres:
    image: chrisnharvey/magiclamp-postgres:${MAGICLAMP_VERSION}

    ports:
      - 5432:5432

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

    networks:
      app_net:
        ipv4_address: 10.0.10.15

  pgadmin:
    image: chrisnharvey/magiclamp-pgadmin:${MAGICLAMP_VERSION}

    networks:
      app_net:
        ipv4_address: 10.0.10.16

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-magiclamp@magiclamp.app}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-magicLAMP}"

    dns: 10.0.10.2

  mysql:
    image: chrisnharvey/magiclamp-mysql:${MAGICLAMP_VERSION}

    volumes:
      - mysql_data:/var/lib/mysql
    
    command: --default-authentication-plugin=mysql_native_password

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

    ports:
      - 3306:3306

    networks:
      app_net:
        ipv4_address: 10.0.10.20

  phpmyadmin:
    image: chrisnharvey/magiclamp-phpmyadmin:${MAGICLAMP_VERSION}

    networks:
      app_net:
        ipv4_address: 10.0.10.22

    environment:
      - PMA_HOST=10.0.10.20
      - PMA_USER=root
      - PMA_PASSWORD=
      - MYSQL_ROOT_PASSWORD=gg

  mailcatcher:
    image: chrisnharvey/magiclamp-mailcatcher:${MAGICLAMP_VERSION}

    ports:
      - 1025:1025

    networks:
      app_net:
        ipv4_address: 10.0.10.25

  workspace:
    image: chrisnharvey/magiclamp-workspace:${MAGICLAMP_VERSION}

    volumes:
      - ${PROJECTS_DIR:-./data/projects}:/projects
      - ${SSH_DIR:-./data/ssh}:/home/magicLAMP/.ssh
      - home_dir:/home/magicLAMP
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/magicLAMP

    tty: true

    working_dir: /projects

    dns: 10.0.10.2

    networks:
      app_net:
        ipv4_address: 10.0.10.5

  dns_internal:
    image: chrisnharvey/magiclamp-dns-internal:${MAGICLAMP_VERSION}

    volumes:
        - ./conf/default/dns_internal/dnsmasq.conf:/etc/dnsmasq.conf

    networks:
      app_net:
        ipv4_address: 10.0.10.2

  dns:
    image: chrisnharvey/magiclamp-dns:${MAGICLAMP_VERSION}

    volumes:
      - ./conf/default/dns/dnsmasq.conf:/etc/dnsmasq.conf

    ports:
      - 127.0.0.1:53:53/udp

    restart: unless-stopped


  redis:
    image: chrisnharvey/magiclamp-redis:${MAGICLAMP_VERSION}

    ports:
      - 6379:6379

    networks:
      app_net:
        ipv4_address: 10.0.10.21

  elasticsearch:
    image: chrisnharvey/magiclamp-elasticsearch-1

    ports:
      - 9200:9200
      - 9300:9300

    environment:
      - discovery.type=single-node

    networks:
      app_net:
        ipv4_address: 10.0.10.92

  selenium_chrome:
    image: chrisnharvey/magiclamp-selenium-chrome:${MAGICLAMP_VERSION}

    ports:
      - 4444:4444
      - 4449:5900

    volumes:
      - /dev/shm:/dev/shm

    networks:
      app_net:
        ipv4_address: 10.0.10.30

    dns: 10.0.10.2

  selenium_firefox:
    image: chrisnharvey/magiclamp-selenium-firefox:${MAGICLAMP_VERSION}

    ports:
      - 5555:4444
      - 5559:5900

    volumes:
      - /dev/shm:/dev/shm

    networks:
      app_net:
        ipv4_address: 10.0.10.31

    dns: 10.0.10.2

  php56:
      image: chrisnharvey/magiclamp-php56:${MAGICLAMP_VERSION}

      volumes:
        - ${PROJECTS_DIR:-./data/projects}:/projects
        - ./conf/default/php/5.6/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/default/php/5.6/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.56

      dns: 10.0.10.2

  php70:
      image: chrisnharvey/magiclamp-php70:${MAGICLAMP_VERSION}

      volumes:
        - ${PROJECTS_DIR:-./data/projects}:/projects
        - ./conf/default/php/7.0/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/default/php/7.0/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.70

      dns: 10.0.10.2

  php71:
      image: chrisnharvey/magiclamp-php71:${MAGICLAMP_VERSION}

      volumes:
        - ${PROJECTS_DIR:-./data/projects}:/projects
        - ./conf/default/php/7.1/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/default/php/7.1/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.71

      dns: 10.0.10.2

  php72:
      image: chrisnharvey/magiclamp-php72:${MAGICLAMP_VERSION}

      volumes:
        - ${PROJECTS_DIR:-./data/projects}:/projects
        - ./conf/default/php/7.2/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/default/php/7.2/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.72

      dns: 10.0.10.2

  php73:
      image: chrisnharvey/magiclamp-php73:${MAGICLAMP_VERSION}

      volumes:
        - ${PROJECTS_DIR:-./data/projects}:/projects
        - ./conf/default/php/7.3/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/default/php/7.3/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.73

      dns: 10.0.10.2

  php74:
      image: chrisnharvey/magiclamp-php74:${MAGICLAMP_VERSION}

      volumes:
        - ${PROJECTS_DIR:-./data/projects}:/projects
        - ./conf/default/php/7.4/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ./conf/default/php/7.4/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-magicLAMP.conf

      working_dir: /projects

      user: ${USER_UID}:${USER_GID}

      networks:
        app_net:
          ipv4_address: 10.0.10.74

      dns: 10.0.10.2

networks:
  app_net:
    driver: bridge

    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 10.0.10.0/24

volumes:
  mysql_data:

  pgadmin_data:

  home_dir:
