site_name: magicLAMP
theme:
  name: material
  favicon: null
  logo:
    icon: code

nav:
  - index.md

  - Installation and Upgrading:
      - installation-and-upgrading/installation.md
      - installation-and-upgrading/upgrading.md

  - PHP:
    - php/switching-version.md

  - MySQL: mysql/index.md

  - PostgreSQL: postgresql/index.md

  - Redis: redis/index.md

  - MailCatcher (SMTP): mailcatcher/index.md

  - Selenium:
    - selenium/index.md
    - selenium/firefox.md
    - selenium/chrome.md