site_name: magicLAMP
site_description: A simple Docker setup for local PHP development
site_author: Chris Harvey
site_url: https://magiclamp.app

theme:
  name: material
  favicon: null
  logo:
    icon: code

repo_name: 'chrisnharvey/magicLAMP'
repo_url: 'https://github.com/chrisnharvey/magicLAMP'

copyright: 'Copyright &copy; Chris Harvey'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/chrisnharvey/magicLAMP'
    - type: 'twitter'
      link: 'https://twitter.com/chrisnharvey'

nav:
  - index.md

  - Installation and Upgrading:
      - installation-and-upgrading/installation.md
      - installation-and-upgrading/upgrading.md

  - Workspace:
    - Introduction: workspace/index.md
    - workspace/accessing-the-shell.md

  - Automatic DNS: automatic-dns/index.md

  - Automatic SSL: automatic-ssl/index.md

  - PHP:
    - php/switching-version.md

  - MySQL: mysql/index.md

  - PostgreSQL: postgresql/index.md

  - Redis: redis/index.md

  - MailCatcher (SMTP): mailcatcher/index.md

  - Selenium:
    - selenium/index.md
    - selenium/firefox.md
    - selenium/chrome.md

  - IDE Integration:
    - ide-integration/vscode.md

  - Extending magicLAMP:
    - extending-magiclamp/docker-compose-overrides.md

  - Troubleshooting:
    - troubleshooting/magiclamp-fails-to-start-on-ubuntu.md
