name: Build

on:
  push:
  
  schedule:
    - cron:  '0 18 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        email: ${{ secrets.DOCKER_EMAIL }}
        
    - name: Build and push images to registry
      run: scripts/build.sh
