name: Build

on:
  push:

  pull_request:

  schedule:
    - cron:  '0 18 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install tooling
      run: |
        curl -fsSL https://goss.rocks/install | sudo sh
        curl -LO https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dcgoss/dcgoss
        chmod +x dcgoss
        sudo mv dcgoss /usr/local/bin

    - uses: actions/checkout@v1

    - name: Build Docker Images
      run: scripts/build-all-parallel.sh

    - name: Test Docker Images
      run: scripts/test.sh

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        email: ${{ secrets.DOCKER_EMAIL }}

    - name: Push Docker Images
      run: scripts/push.sh