name: Build

on:
  push:

  pull_request:

  schedule:
    - cron:  '0 18 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker Images
      run: scripts/build.sh

    - name: Test Docker Images
      run: scripts/test.sh

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        email: ${{ secrets.DOCKER_EMAIL }}

    - name: Push Docker Images
      run: scripts/push.sh